{
 "title": "Dude Dashboard",
 "time": { "from": "2023-08-11T08:17:09.564Z", "to": "2023-08-11T10:33:13.111Z" },
 "panels": [
  {
   "title": "Distance",
   "type": "stat",
   "description": "Based on Ground Speed",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nfrom(bucket: \"dude\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"datalog\")\n    |> filter(fn: (r) => r._field == \"GS\" )\n    |> map(fn: (r) => ({r with _value: r._value * 0.514444 / 1000.0}))\n    |> sum()\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consomation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FuelRemaining\")\n\nmin = data\n  |> min()\n\nmax = data\n  |> max()\n\njoin(tables: {min: min, max: max}, on: [\"_start\", \"_field\", \"_start\", \"_measurement\"], method: \"inner\")\n  |> map(fn: (r) => ({ r with _value: r._value_max * 3.8 - r._value_min * 3.8 }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FuelRemaining\")\n  |> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg FuelFlow",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FuelFlow\")\n  |> map(fn: (r) => ({r with _value: r._value * 3.8}))\n  |> mean()\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max RPM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RPM\")\n  |> max()\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg RPM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RPM\")\n  |> mean()\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg MAP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MAP\")\n  |> mean()\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Gnd Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GS\")\n  |> max()\n  |> map(fn: (r) => ({r with _value: r._value * 1.832}))\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Gnd Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GS\")\n  |> mean()\n  |> map(fn: (r) => ({r with _value: r._value * 1.832}))\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max TAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TAS\")\n  |> max()\n  |> map(fn: (r) => ({r with _value: r._value * 1.832}))\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg TAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data = from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TAS\")\n  |> mean()\n  |> map(fn: (r) => ({r with _value: r._value * 1.832}))\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Geo",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 28, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Parameters",
   "type": "graph",
   "gridPos": { "h": 28, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"dude\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"datalog\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}